name: Github-Pages-push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./media
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.57.2'
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir
      
      - name: Pushes test folder
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: './*'
          destination_repo: 'media-minibear2333/media-minibear2333.github.io'
          destination_folder: './'
          user_email: 'pzqu@qq.com'
          user_name: 'minibear2333'
          commit_msg: '[GHA] Update the test files.'

